apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: Ym9vay1yZHNzLmM1ZWkyY2VpY2Y5bi5jYS1jZW50cmFsLTEucmRzLmFtYXpvbmF3cy5jb20=
  db_username: YWRtaW4=
  db_password: aGVtYW50aDEyMw==

