apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: LXIgYm9vay1yZHMuYzVlaTJjZWljZjluLmNhLWNlbnRyYWwtMS5yZHMuYW1hem9uYXdzLmNvbQo=
  db_username: YWRtaW4=
  db_password: aGVtYW50aDEyMw==

